name: Publish package to GitHub Packages
on:
  # 这里是只有master分支发生 push 或者 pull事件时才会触发action运行
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display the path ls
        run:  echo $(ls $GITHUB_WORKSPACE)

      #构建镜像
      - name: Build And Push Docker image
        env:
          # 指定自己的仓库地址
          docker_repo: registry.cn-hangzhou.aliyuncs.com/hanwb
          # 指定镜像名称
          image_name: devops-java
          # 指定镜像标签
          tag: latest
        run: | 
          # 查看docker 版本
          docker version
          # 进入工作目录
          cd $GITHUB_WORKSPACE
          # 登录阿里云镜像仓库， 这里登录docker的用户名和密码在Secrets中设置，下面有介绍
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
          # 使用Dockerfile构建镜像
          docker build . --file Dockerfile --tag $docker_repo/$image_name:$tag
          # 推送镜像到镜像仓库
          docker push $docker_repo/$image_name:$tag

